# Create: conda env create -f environment.yml
# Update:  conda env update -f environment.yml --prune
name: asr-speech-generation
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - libsndfile
  - pip:
    - -r requirements.txt